apiVersion: apps/v1
kind: Deployment
metadata:
  name: codesnippetsapi
spec:
  selector:
    matchLabels:
      app: codesnippetsapi
  replicas: 2
  template:
    metadata:
      labels:
        app: codesnippetsapi
    spec:
      containers:
      - name: codesnippetsapi
        image: bnarasimha21/codesnippetsapi:1.0
        ports:
        - containerPort: 4000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: codesnippetsapi-service
spec:
    type: ClusterIP
    selector:
        app: codesnippetsapi    
    ports:
        - protocol: TCP
          port: 4000
          targetPort: 4000
